# Generated by Django 3.1.7 on 2021-03-19 06:47

import auditory.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Audio description'),
        ),
        migrations.AddField(
            model_name='audio',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='thumbnail', verbose_name='Audio thumbnail'),
        ),
        migrations.AlterField(
            model_name='audio',
            name='audiofile',
            field=models.FileField(upload_to='audio', validators=[auditory.validators.validate_file_extension, auditory.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='audio',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Audio name'),
        ),
    ]
