# Generated by Django 3.1.7 on 2021-04-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0003_auto_20210403_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='author',
            field=models.CharField(blank=True, default='Not Available', max_length=30, null=True),
        ),
    ]
