# Generated by Django 3.1.7 on 2021-04-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0004_audio_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='duration',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
