# Generated by Django 3.1.7 on 2021-04-09 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditory', '0005_audio_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='audio',
            name='uploaded',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
