name: wisdom-ci

on:
  push:
    branches: [main, develop, github-action]
  pull_request:
    branches: [main, develop, github-action]

jobs:

  lint:
    name: Linter
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      # Checkout repository
      - uses: actions/checkout@v1
      # Setup python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install dependecies
      - name: Install tox
        run: |
            python -m pip install --upgrade pip
            pip install tox tox-gh-actions
      # Execute linter
      - name: Tox lint
        run: |
            tox -e lintenv:
        env:
          SYSTEM_ENV: cicd
  
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      # Checkout repository
      - uses: actions/checkout@v1
      # Setup python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      # Install dependecies
      - name: Install tox
        run: |
            python -m pip install --upgrade pip
            pip install tox tox-gh-actions
      # Execute test
      - name: Tox test
        run: |
            tox -e test
        env:
          SYSTEM_ENV: cicd
